---
# tasks file for roles/firewall_defense
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Set Default Policy to Deny Incoming
  ufw:
    direction: incoming
    policy: deny

- name: Allow SSH with Rate Limiting
  ufw:
    rule: limit
    port: "{{ item }}"
    proto: tcp
  loop: "{{ allowed_ports }}"

- name: Enable UFW
  ufw:
    state: enabled

- name: PANIC MODE - Flush all firewall rules
  iptables:
    flush: yes
  when: panic_mode

- name: PANIC MODE - Set default INPUT policy to DROP
  iptables:
    chain: INPUT
    policy: DROP
  when: panic_mode

- name: PANIC MODE - Drop ICMP (Ping)
  iptables:
    chain: INPUT
    protocol: icmp
    jump: DROP
  when: panic_mode



